SELECT  DATE_FORMAT(O.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT 
FROM ONLINE_SALE O 
WHERE O.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION ALL

SELECT DATE_FORMAT(P.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, P.PRODUCT_ID, NULL AS USER_ID, P.SALES_AMOUNT 
FROM OFFLINE_SALE P
WHERE P.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
