-- 코드를 입력하세요
SELECT I.FOOD_TYPE,I.REST_ID,I.REST_NAME,I.FAVORITES 
FROM REST_INFO I
JOIN (SELECT FOOD_TYPE,MAX(FAVORITES) AS MAX_FAV
      FROM REST_INFO  
      GROUP BY  FOOD_TYPE) AS MAX_FAV_RES_TYPE
ON (I.FOOD_TYPE = MAX_FAV_RES_TYPE.FOOD_TYPE) AND (I.FAVORITES = MAX_FAV_RES_TYPE.MAX_FAV)
ORDER BY FOOD_TYPE DESC;
