SELECT F.CATEGORY,F.PRICE,F.PRODUCT_NAME 
FROM FOOD_PRODUCT F
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE 
      FROM FOOD_PRODUCT 
      WHERE CATEGORY IN ('과자','국','김치','식용유')
      GROUP BY CATEGORY) AS MAX_FP 
ON F.CATEGORY = MAX_FP.CATEGORY AND F.PRICE = MAX_FP.MAX_PRICE
ORDER BY F.PRICE DESC;